name: CI-reference-web-app

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'apps/reference-web-app/**'
      - 'packages/**'
      - 'package.json'
      - 'yarn.lock'
      - '.yarnrc.yml'
      - '*.base.json'
      - '*.base.js'
      - '.prettier*.*'
      - '.github/workflows/**'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    # Optional:
    #   Only consider those files/paths to trigger the github action
    #   to prevent unnecessary builds.
    paths:
      - 'apps/reference-web-app/**'
      - 'packages/**'
      - 'package.json'
      - 'yarn.lock'
      - '.yarnrc.yml'
      - '*.base.json'
      - '*.base.js'
      - '.prettier*.*'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Why not using setup-node 2.2+ cache option (yet) ?
      # see https://github.com/belgattitude/nextjs-monorepo-example/pull/369
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-cache-folder-

      # see https://github.com/vercel/next.js/pull/27362
      - name: Restore nextjs build reference-web-app from cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/apps/reference-web-app/.next/cache
            ${{ github.workspace }}/.cache
            ${{ github.workspace }}/**/tsconfig.tsbuildinfo
            ${{ github.workspace }}/**/.eslintcache

          key: ${{ runner.os }}-nextjs-reference-web-app-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('apps/reference-web-app/src/**.[jt]sx?', 'apps/reference-web-app/src/**.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-reference-web-app-${{ hashFiles('**/yarn.lock') }}-

      - name: Install dependencies
        run: |
          yarn install --immutable
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Typecheck
        working-directory: apps/reference-web-app
        run: |
          yarn typecheck

      - name: Linter
        working-directory: apps/reference-web-app
        run: |
          yarn lint --cache

      - name: Unit tests
        working-directory: apps/reference-web-app
        run: |
          yarn ci-test:unit

      - name: Build reference-web-app
        working-directory: apps/reference-web-app
        run: |
          yarn build
        env:
          # Speed up build: they are linted in a previous step
          NEXTJS_IGNORE_ESLINT: 1
          # Speed up build: they are typechecked in a previous step
          NEXTJS_IGNORE_TYPECHECK: 1
          # Speed up build: don't run if not needed, enable if it becomes needed
          NEXT_DISABLE_SOURCEMAPS: 1
          # Don't send telemetry for ci
          NEXT_TELEMETRY_DISABLED: 1
          # Fully disable sentry registration here (no overhead in build time)
          NEXT_DISABLE_SENTRY: 1
          # Disable sentry source map upload (when not needed)
          NEXT_SENTRY_DRY_RUN: 1

      - name: Check bundle size
        working-directory: apps/reference-web-app
        run: |
          yarn bundle:check-size

      - name: Install Playwright
        run: npx playwright install --with-deps chromium webkit

      - name: E2E run web-app playwright tests
        working-directory: apps/reference-web-app
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- yarn test:e2e
        env:
          E2E_SKIP_NEXTJS_BUILD: 1
          CI: 1

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: web-app-playwright-test-results
          path: apps/reference-web-app/e2e/.out
